import { jsPDF } from "jspdf";
import {
  applyDefaultFont,
  drawHorizontalRule,
  getContentWidth,
  ORGANIZATION,
  PDF_COLORS,
  PDF_MARGINS,
  PDF_PAGE,
  setPrimaryColor,
  truncateForPdf,
} from "@/lib/pdf/fonts";
import { formatCurrency, formatDate, formatQuantity } from "@/lib/utils/formatters";

type DocumentHeader = {
  titleEn: string;
  titleSi: string;
  documentNo: string;
  date: Date | string;
};

type LineItem = {
  itemCode: string;
  nameEn: string;
  quantity: number;
  unit: string;
  unitPrice?: number;
};

function drawLetterhead(doc: jsPDF, header: DocumentHeader): number {
  let y = PDF_MARGINS.top;

  doc.setFontSize(14);
  setPrimaryColor(doc);
  doc.text(ORGANIZATION.nameEn, PDF_MARGINS.left, y);
  y += 6;

  doc.setFontSize(8);
  doc.setTextColor(...PDF_COLORS.muted);
  doc.text(ORGANIZATION.address, PDF_MARGINS.left, y);
  y += 4;
  doc.text(`${ORGANIZATION.phone} | ${ORGANIZATION.email}`, PDF_MARGINS.left, y);
  y += 8;

  drawHorizontalRule(doc, y);
  y += 8;

  doc.setFontSize(16);
  setPrimaryColor(doc);
  doc.text(header.titleEn, PDF_MARGINS.left, y);
  y += 6;

  doc.setFontSize(10);
  doc.setTextColor(...PDF_COLORS.secondary);
  doc.text(header.titleSi, PDF_MARGINS.left, y);
  y += 10;

  doc.setFontSize(10);
  doc.text(`Document No: ${header.documentNo}`, PDF_MARGINS.left, y);
  doc.text(`Date: ${formatDate(header.date)}`, PDF_PAGE.width - PDF_MARGINS.right - 40, y);
  y += 8;

  drawHorizontalRule(doc, y);
  return y + 6;
}

function drawLineItemsTable(
  doc: jsPDF,
  startY: number,
  lines: LineItem[],
  showPrice: boolean,
): number {
  let y = startY;
  const colWidths = showPrice ? [25, 70, 25, 20, 30] : [30, 90, 30, 20];
  const headers = showPrice
    ? ["Code", "Description", "Qty", "Unit", "Amount"]
    : ["Code", "Description", "Qty", "Unit"];

  doc.setFillColor(...PDF_COLORS.headerBg);
  doc.rect(PDF_MARGINS.left, y, getContentWidth(), 8, "F");

  applyDefaultFont(doc, "bold");
  let x = PDF_MARGINS.left + 2;
  headers.forEach((header, i) => {
    doc.text(header, x, y + 5.5);
    x += colWidths[i] ?? 0;
  });
  y += 10;

  applyDefaultFont(doc);
  let total = 0;

  for (const line of lines) {
    if (y > PDF_PAGE.height - PDF_MARGINS.bottom - 20) {
      doc.addPage();
      y = PDF_MARGINS.top;
    }

    x = PDF_MARGINS.left + 2;
    const amount = (line.unitPrice ?? 0) * line.quantity;
    total += amount;

    const cells = showPrice
      ? [
          line.itemCode,
          truncateForPdf(line.nameEn, 35),
          formatQuantity(line.quantity),
          line.unit,
          formatCurrency(amount),
        ]
      : [line.itemCode, truncateForPdf(line.nameEn, 45), formatQuantity(line.quantity), line.unit];

    cells.forEach((cell, i) => {
      doc.text(String(cell), x, y);
      x += colWidths[i] ?? 0;
    });
    y += 7;
  }

  if (showPrice) {
    y += 4;
    drawHorizontalRule(doc, y);
    y += 6;
    applyDefaultFont(doc, "bold");
    doc.text("Total:", PDF_MARGINS.left + colWidths[0]! + colWidths[1]!, y);
    doc.text(
      formatCurrency(total),
      PDF_MARGINS.left + colWidths.slice(0, 4).reduce((a, b) => a + b, 0),
      y,
    );
  }

  return y + 10;
}

function drawFooter(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...PDF_COLORS.muted);
    doc.text(`Page ${i} of ${pageCount}`, PDF_PAGE.width / 2, PDF_PAGE.height - 10, {
      align: "center",
    });
    doc.text("Generated by IrrWMS", PDF_MARGINS.left, PDF_PAGE.height - 10);
  }
}

export type GRNTemplateData = DocumentHeader & {
  supplierName: string;
  warehouseName: string;
  receivedBy: string;
  lines: LineItem[];
  remarks?: string;
};

export function generateGRNPdf(data: GRNTemplateData): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  applyDefaultFont(doc);

  let y = drawLetterhead(doc, data);

  doc.setFontSize(10);
  doc.text(`Supplier: ${data.supplierName}`, PDF_MARGINS.left, y);
  y += 5;
  doc.text(`Warehouse: ${data.warehouseName}`, PDF_MARGINS.left, y);
  y += 5;
  doc.text(`Received By: ${data.receivedBy}`, PDF_MARGINS.left, y);
  y += 10;

  y = drawLineItemsTable(doc, y, data.lines, true);

  if (data.remarks) {
    doc.text(`Remarks: ${data.remarks}`, PDF_MARGINS.left, y);
    y += 10;
  }

  y += 15;
  doc.text("Received By: _______________", PDF_MARGINS.left, y);
  doc.text("Approved By: _______________", PDF_PAGE.width / 2, y);

  drawFooter(doc);
  return doc;
}

export type GINTemplateData = DocumentHeader & {
  issuedTo: string;
  warehouseName: string;
  purpose?: string;
  lines: LineItem[];
  remarks?: string;
};

export function generateGINPdf(data: GINTemplateData): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  applyDefaultFont(doc);

  let y = drawLetterhead(doc, data);

  doc.text(`Issued To: ${data.issuedTo}`, PDF_MARGINS.left, y);
  y += 5;
  doc.text(`Warehouse: ${data.warehouseName}`, PDF_MARGINS.left, y);
  y += 5;
  if (data.purpose) {
    doc.text(`Purpose: ${data.purpose}`, PDF_MARGINS.left, y);
    y += 5;
  }
  y += 5;

  y = drawLineItemsTable(doc, y, data.lines, false);

  if (data.remarks) {
    doc.text(`Remarks: ${data.remarks}`, PDF_MARGINS.left, y);
  }

  y += 20;
  doc.text("Issued By: _______________", PDF_MARGINS.left, y);
  doc.text("Received By: _______________", PDF_PAGE.width / 2, y);

  drawFooter(doc);
  return doc;
}

export type StockReportData = {
  titleEn: string;
  titleSi: string;
  warehouseName: string;
  fromDate: Date | string;
  toDate: Date | string;
  generatedBy: string;
  lines: Array<LineItem & { currentStock?: number; value?: number }>;
};

export function generateStockReportPdf(data: StockReportData): jsPDF {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  applyDefaultFont(doc);

  const header: DocumentHeader = {
    titleEn: data.titleEn,
    titleSi: data.titleSi,
    documentNo: `RPT-${Date.now()}`,
    date: new Date(),
  };

  let y = drawLetterhead(doc, header);
  doc.text(`Warehouse: ${data.warehouseName}`, PDF_MARGINS.left, y);
  y += 5;
  doc.text(
    `Period: ${formatDate(data.fromDate)} — ${formatDate(data.toDate)}`,
    PDF_MARGINS.left,
    y,
  );
  y += 5;
  doc.text(`Generated By: ${data.generatedBy}`, PDF_MARGINS.left, y);
  y += 10;

  drawLineItemsTable(
    doc,
    y,
    data.lines.map((l) => ({
      itemCode: l.itemCode,
      nameEn: l.nameEn,
      quantity: l.currentStock ?? l.quantity,
      unit: l.unit,
      unitPrice: l.unitPrice,
    })),
    true,
  );

  drawFooter(doc);
  return doc;
}

export function pdfToBuffer(doc: jsPDF): Buffer {
  const arrayBuffer = doc.output("arraybuffer");
  return Buffer.from(arrayBuffer);
}

export function pdfToDataUri(doc: jsPDF): string {
  return doc.output("datauristring");
}
