#!/usr/bin/env bash
# Concatenate supabase/migrations/*.sql into supabase/sql/apply_in_sql_editor.sql
# for one-shot paste in Supabase Dashboard → SQL Editor.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MIGRATIONS_DIR="$ROOT_DIR/supabase/migrations"
OUTPUT="$ROOT_DIR/supabase/sql/apply_in_sql_editor.sql"

if [[ ! -d "$MIGRATIONS_DIR" ]]; then
  echo "ERROR: $MIGRATIONS_DIR not found" >&2
  exit 1
fi

FILES=()
while IFS= read -r file; do
  FILES+=("$file")
done < <(find "$MIGRATIONS_DIR" -maxdepth 1 -name '*.sql' | sort)

if [[ ${#FILES[@]} -eq 0 ]]; then
  echo "ERROR: no .sql files in $MIGRATIONS_DIR" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT")"

{
  cat <<'HEADER'
-- =============================================================================
-- IrrWMS — paste this ENTIRE file into Supabase Dashboard → SQL Editor → Run
-- Prerequisites: empty database (new project) or reset dev branch first.
-- Generated by: npm run db:supabase:bundle (scripts/build-supabase-sql.sh)
-- Do not edit by hand; edit supabase/migrations/*.sql and re-run the bundle script.
-- =============================================================================

HEADER

  for file in "${FILES[@]}"; do
    name="$(basename "$file")"
    printf '\n-- >>> migrations/%s\n' "$name"
    cat "$file"
    printf '\n'
  done
} >"$OUTPUT"

echo "==> Wrote ${#FILES[@]} migration(s) to $OUTPUT"
