#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MIGRATIONS_DIR="$ROOT_DIR/supabase/migrations"
OUT_FILE="$ROOT_DIR/supabase/sql/apply_in_sql_editor.sql"

echo "==> Building $OUT_FILE"

{
  cat <<'HEADER'
-- =============================================================================
-- IrrWMS — paste this ENTIRE file into Supabase Dashboard → SQL Editor → Run
-- Prerequisites: empty database (new project) or reset dev branch first.
-- Generated by: npm run db:supabase:bundle (scripts/build-supabase-sql.sh)
-- Do not edit by hand; edit supabase/migrations/*.sql and re-run the bundle script.
-- =============================================================================

HEADER

  for f in "$MIGRATIONS_DIR"/*.sql; do
    [[ -f "$f" ]] || continue
    echo ""
    echo "-- >>> migrations/$(basename "$f")"
    cat "$f"
    echo ""
  done
} > "$OUT_FILE"

echo "==> Wrote $(wc -l < "$OUT_FILE" | tr -d ' ') lines to $OUT_FILE"
