#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

MIGRATIONS_DIR="supabase/migrations"
OUT_FILE="supabase/sql/apply_in_sql_editor.sql"

echo "==> Syncing Prisma checksum into migration 04"
node scripts/compute-prisma-checksum.mjs

echo "==> Building ${OUT_FILE}"

{
  cat <<'HEADER'
-- =============================================================================
-- IrrWMS — paste this ENTIRE file into Supabase Dashboard → SQL Editor → Run
-- Prerequisites: empty database (new project) or reset dev branch first.
-- Generated by: npm run db:supabase:bundle (scripts/build-supabase-sql.sh)
-- Do not edit by hand; edit supabase/migrations/*.sql and re-run the bundle script.
-- =============================================================================

HEADER

  shopt -s nullglob
  for file in "${MIGRATIONS_DIR}"/[0-9]*_*.sql; do
    rel="${file#${MIGRATIONS_DIR}/}"
    echo ""
    echo "-- >>> migrations/${rel}"
    cat "$file"
    echo ""
  done
} > "$OUT_FILE"

echo "==> Wrote $(wc -l < "$OUT_FILE" | tr -d ' ') lines to ${OUT_FILE}"
